base_url = "https://umbra-sphere.lucka.dev"
title = "Umbra Sphere"
description = "Discover the world, with the power of SÂ²Geometry."

build_search_index = false
compile_sass = true
minify_html = true

theme = "apollo"

[markdown]
highlight_code = true

[extra]
favicon = "/app-icon-64@3x.png"
menu = [
  { name = "Privacy", url = "/privacy", weight = 1 },
  { name = "Contact", url = "/contact", weight = 2 },
]
socials = []
theme = "toggle"
